# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalurl', models.CharField(max_length=1000)),
                ('shorten', models.CharField(max_length=500)),
            ],
        ),
    ]
