# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0003_auto_20160624_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sam',
            name='clicks',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
